import fs from 'node:fs';
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
const index=fs.readFileSync('index.html','utf8');
const build=fs.readFileSync('build.mjs','utf8');
const runtime=fs.readFileSync('csp-runtime.js','utf8');
const fail=[];const need=(c,m)=>{if(!c)fail.push(m);};
need(pkg.version==='31.25.0',`Versión inesperada ${pkg.version}`);
need(index.includes('trading-research-source-version" content="31.25.0"'),'source-version no es 31.25.0.');
need(index.includes('<script src="style-attr-runtime.js"></script>'),'index.html no carga style-attr-runtime.js.');
need(index.includes('<script src="cloud-v10-runtime.js"></script>'),'index.html no carga cloud-v10-runtime.js.');
need(index.includes('<script src="exit-lab-runtime.js"></script>'),'index.html no carga exit-lab-runtime.js.');
need(index.includes('<script src="canonical-metrics-runtime.js"></script>'),'index.html no carga canonical-metrics-runtime.js.');
need(index.indexOf('exit-lab-runtime.js')>index.indexOf('event-runtime.js')&&index.indexOf('exit-lab-runtime.js')<index.indexOf('canonical-metrics-runtime.js'),'Exit Lab V31.24 debe cargar después del Action Registry y antes de métricas canónicas.');
need(index.indexOf('canonical-metrics-runtime.js')>index.indexOf('exit-lab-runtime.js')&&index.indexOf('canonical-metrics-runtime.js')<index.indexOf('csp-runtime.js'),'Métricas canónicas deben cargar después de Exit Lab y antes de CSP runtime.');
need(index.includes('<script src="csp-runtime.js"></script>'),'index.html no carga csp-runtime.js.');
need(index.indexOf('cloud-v10-runtime.js')>index.indexOf('event-runtime.js')&&index.indexOf('cloud-v10-runtime.js')<index.indexOf('blob-lifecycle-runtime.js'),'Cloud V10 debe cargar después del Action Registry y antes de Blob Lifecycle.');
need(index.indexOf('style-attr-runtime.js')>index.indexOf('app.js'),'style-attr-runtime.js debe cargar después de app.js.');
need(index.includes('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.112.3/dist/umd/supabase.js'),'Supabase SDK no está fijado a 2.112.3 UMD.');
need(!index.includes('@supabase/supabase-js@2"></script>'),'Supabase conserva la versión flotante @2.');
need(runtime.includes("const TR_CSP_RUNTIME_VERSION='31.24.0'"),'Runtime CSP con versión incorrecta.');
need(runtime.includes('styleAttrNone:true'),'El runtime CSP no exige style-src-attr none.');
need(!runtime.includes('supabaseOnly'),'El contrato CSP conserva el nombre engañoso supabaseOnly.');
need(runtime.includes('supabaseConnectRequired:true'),'El contrato CSP no declara explícitamente que requiere conexión Supabase.');
need(runtime.includes('supabaseSdkPinned:true'),'El contrato CSP no declara explícitamente que requiere SDK Supabase fijado.');
need(runtime.includes("fetch(location.href,{method:'HEAD'"),'Falta sonda runtime de cabecera CSP.');
need(runtime.includes('headerMatchesExpectedPolicy'),'El diagnóstico CSP no nombra exactamente la evidencia de cabecera.');
need(runtime.includes('ok:s.checked?'),'El diagnóstico CSP no conserva estado desconocido antes de la sonda.');
need(!runtime.includes('strictExecutableBoundary'),'El diagnóstico CSP conserva un claim ejecutable más amplio que la evidencia.');
need(!runtime.includes('fullStrictStyles'),'El diagnóstico CSP conserva un claim de estilos más amplio que la evidencia.');
need(build.includes("fs.writeFileSync('dist/_headers'"),'Build no genera _headers.');
need(build.includes("script-src-attr 'none'"),'Build no bloquea script-src-attr.');
need(build.includes("style-src-attr 'none'"),'Build no bloquea style-src-attr.');
need(!build.includes("style-src-attr 'unsafe-inline'"),'Build conserva compatibilidad unsafe-inline para estilos.');
need(!/unsafe-eval/.test(build),'Build contiene unsafe-eval.');
need(!/unsafe-inline[^'\"]*['\"]?[^\n]*script-src/.test(build),'Build parece permitir unsafe-inline para scripts.');
if(fail.length){console.error('CSP source verification FAILED');for(const f of fail)console.error(' - '+f);process.exit(1);}
console.log('CSP policy source verification OK');
console.log(' - Supabase SDK: pinned 2.112.3 UMD');
console.log(' - script-src-attr: none');
console.log(' - unsafe-eval: absent');
console.log(' - style-src-attr: none');
console.log(' - Runtime status: unknown until HEAD probe; success means header matches expected policy');
