import fs from 'node:fs';
import {transformStyleAttrs,styleTransformSelfTest} from './html-style-transform.mjs';
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
const files=['app.js','style-attr-runtime.js','reports-purity-runtime.js','structural-runtime.js','state-runtime.js','persistence-coalescing-runtime.js','security-runtime.js','event-runtime.js','csp-runtime.js','style-runtime.js','operation-cleanup-runtime.js','render-closure-runtime.js','index.html'];
const text=files.map(f=>fs.readFileSync(f,'utf8')).join('\n');
const inlineAttributes=[...text.matchAll(/\bstyle\s*=\s*["']/gi)].length;
const cssomWrites=[...text.matchAll(/\.style\.[A-Za-z_$][\w$]*\s*=/g)].length+[...text.matchAll(/setAttribute\s*\(\s*["']style["']/gi)].length;
const runtime=fs.readFileSync('style-runtime.js','utf8');
const boundary=fs.readFileSync('style-attr-runtime.js','utf8');
const build=fs.readFileSync('build.mjs','utf8');
const index=fs.readFileSync('index.html','utf8');
const fail=[];const need=(c,m)=>{if(!c)fail.push(m);};
need(pkg.version==='31.25.0',`Versión inesperada ${pkg.version}`);
need(index.includes('<script src="style-attr-runtime.js"></script>'),'index.html no carga style-attr-runtime.js.');
need(index.includes('<script src="style-runtime.js"></script>'),'index.html no carga style-runtime.js.');
need(index.includes('<script src="render-closure-runtime.js"></script>'),'index.html no carga render-closure-runtime.js.');
need(index.indexOf('style-attr-runtime.js')>index.indexOf('app.js'),'style-attr-runtime.js debe cargar después de app.js.');
need(index.indexOf('style-runtime.js')>index.indexOf('csp-runtime.js'),'style-runtime.js debe cargar después de csp-runtime.js.');
need(index.indexOf('render-closure-runtime.js')>index.indexOf('style-runtime.js'),'render-closure-runtime.js debe cargar después del runtime de estilos.');
need(boundary.includes("const TR_STYLE_ATTR_VERSION='31.22.0'"),'Boundary runtime con versión incorrecta.');
need(boundary.includes("const TR_STYLE_ATTR_SOURCE='data-tr-style'"),'Boundary runtime no usa data-tr-style.');
need(boundary.includes('new MutationObserver(trStyleAttrMutations)'),'Falta hidratación runtime de nuevos tokens de estilo.');
need(boundary.includes('el.style[camel]=value'),'Las propiedades estándar no se aplican mediante CSSOM directo.');
need(boundary.includes('ignoredEmpty:0'),'Boundary no contabiliza no-ops de estilo dinámico vacío.');
need(boundary.includes('if(!raw){trStyleAttrStats.ignoredEmpty++;return;}'),'Atributos de estilo vacíos deberían ser no-op, no rechazo.');
need(boundary.includes("if(!rawValue){trStyleAttrStats.ignoredEmpty++;continue;}"),'Declaraciones dinámicas con valor vacío deberían ser no-op, no rechazo.');
need(boundary.includes('ignoredEmpty:trStyleAttrStats.ignoredEmpty'),'Diagnóstico no expone los no-ops vacíos.');
need(!/\.style\.cssText\s*=/.test(boundary),'Boundary runtime usa cssText, incompatible con style-src-attr none.');
need(!/setAttribute\s*\(\s*["']style["']/.test(boundary),'Boundary runtime usa setAttribute(style), incompatible con style-src-attr none.');
need(runtime.includes("const TR_STYLE_RUNTIME_VERSION='31.22.0'"),'Diagnóstico style runtime con versión incorrecta.');
need(runtime.includes('effectiveInlineAttributes'),'Diagnóstico no muestra atributos style efectivos.');
need(build.includes("from './html-style-transform.mjs'"),'Build no usa el scanner dedicado de atributos style.');
need(build.includes("kind:'open-tag-context-scanner'"),'Inventario de build no identifica el transformador context-aware.');
const self=styleTransformSelfTest();need(self.ok,`Self-test del style scanner falló: ${JSON.stringify(self.failures)}`);
const prose='const note = "style=\\"color:red\\"";';need(transformStyleAttrs(prose).converted===0,'El scanner altera style= fuera de un tag HTML.');
const codeExample='Documentation: style="color:red"';need(transformStyleAttrs(codeExample).source===codeExample,'El scanner altera texto explicativo sin tag.');
need(inlineAttributes>0,'La prueba esperaba deuda histórica en fuente para comprobar la transformación.');
need(cssomWrites>0,'La prueba esperaba escrituras CSSOM directas existentes; son compatibles con style-src-attr none.');
if(fail.length){console.error('Style boundary verification FAILED');for(const f of fail)console.error(' - '+f);process.exit(1);}
console.log('Style boundary verification OK');
console.log(` - Legacy source style attributes: ${inlineAttributes}`);
console.log(` - Direct CSSOM writes in source: ${cssomWrites}`);
console.log(' - Build-time style transform: context-aware opening-tag scanner');
console.log(' - Scanner self-test: prose/code outside HTML tags preserved');
console.log(' - Runtime token hydration: enabled');
console.log(' - Empty dynamic style values: harmless no-op, still observable in diagnostics');
console.log(" - CSP target: style-src-attr 'none'");
