import fs from 'node:fs';
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
const files=['app.js','style-attr-runtime.js','reports-purity-runtime.js','structural-runtime.js','state-runtime.js','security-runtime.js','event-runtime.js','csp-runtime.js','style-runtime.js','index.html'];
const text=files.map(f=>fs.readFileSync(f,'utf8')).join('\n');
const inlineAttributes=[...text.matchAll(/\bstyle\s*=\s*["']/gi)].length;
const cssomWrites=[...text.matchAll(/\.style\.[A-Za-z_$][\w$]*\s*=/g)].length+[...text.matchAll(/setAttribute\s*\(\s*["']style["']/gi)].length;
const runtime=fs.readFileSync('style-runtime.js','utf8');
const boundary=fs.readFileSync('style-attr-runtime.js','utf8');
const build=fs.readFileSync('build.mjs','utf8');
const index=fs.readFileSync('index.html','utf8');
const fail=[];const need=(c,m)=>{if(!c)fail.push(m);};
need(pkg.version==='31.22.0',`Versión inesperada ${pkg.version}`);
need(index.includes('<script src="style-attr-runtime.js"></script>'),'index.html no carga style-attr-runtime.js.');
need(index.includes('<script src="style-runtime.js"></script>'),'index.html no carga style-runtime.js.');
need(index.indexOf('style-attr-runtime.js')>index.indexOf('app.js'),'style-attr-runtime.js debe cargar después de app.js.');
need(index.indexOf('style-runtime.js')>index.indexOf('csp-runtime.js'),'style-runtime.js debe cargar después de csp-runtime.js.');
need(boundary.includes("const TR_STYLE_ATTR_VERSION='31.22.0'"),'Boundary runtime con versión incorrecta.');
need(boundary.includes("const TR_STYLE_ATTR_SOURCE='data-tr-style'"),'Boundary runtime no usa data-tr-style.');
need(boundary.includes('new MutationObserver(trStyleAttrMutations)'),'Falta hidratación runtime de nuevos tokens de estilo.');
need(boundary.includes('el.style[camel]=value'),'Las propiedades estándar no se aplican mediante CSSOM directo.');
need(!/\.style\.cssText\s*=/.test(boundary),'Boundary runtime usa cssText, incompatible con style-src-attr none.');
need(!/setAttribute\s*\(\s*["']style["']/.test(boundary),'Boundary runtime usa setAttribute(style), incompatible con style-src-attr none.');
need(runtime.includes("const TR_STYLE_RUNTIME_VERSION='31.22.0'"),'Diagnóstico style runtime con versión incorrecta.');
need(runtime.includes('effectiveInlineAttributes'),'Diagnóstico no muestra atributos style efectivos.');
need(build.includes('transformStyleAttrs'),'Build no transforma atributos style históricos.');
need(build.includes("style-src-attr 'none'"),'Build no activa la política estricta de style attrs.');
need(inlineAttributes>0,'La prueba esperaba deuda histórica en fuente para comprobar la transformación.');
need(cssomWrites>0,'La prueba esperaba escrituras CSSOM directas existentes; son compatibles con style-src-attr none.');
if(fail.length){console.error('Style boundary verification FAILED');for(const f of fail)console.error(' - '+f);process.exit(1);}
console.log('Style boundary verification OK');
console.log(` - Legacy source style attributes: ${inlineAttributes}`);
console.log(` - Direct CSSOM writes in source: ${cssomWrites}`);
console.log(' - Build-time style attribute transform: enabled');
console.log(' - Runtime token hydration: enabled');
console.log(" - CSP target: style-src-attr 'none'");
