import fs from 'node:fs';
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
const files=['app.js','structural-runtime.js','state-runtime.js','security-runtime.js','event-runtime.js','csp-runtime.js','style-runtime.js','index.html'];
const text=files.map(f=>fs.readFileSync(f,'utf8')).join('\n');
const inlineAttributes=[...text.matchAll(/\bstyle\s*=\s*["']/gi)].length;
const cssomWrites=[...text.matchAll(/\.style\.[A-Za-z_$][\w$]*\s*=/g)].length+[...text.matchAll(/setAttribute\s*\(\s*["']style["']/gi)].length;
const runtime=fs.readFileSync('style-runtime.js','utf8');
const index=fs.readFileSync('index.html','utf8');
const fail=[];const need=(c,m)=>{if(!c)fail.push(m);};
need(pkg.version==='31.21.0',`Versión inesperada ${pkg.version}`);
need(index.includes('<script src="style-runtime.js"></script>'),'index.html no carga style-runtime.js.');
need(index.indexOf('style-runtime.js')>index.indexOf('csp-runtime.js'),'style-runtime.js debe cargar después de csp-runtime.js.');
need(runtime.includes('new MutationObserver(trStyleMutation)'),'Falta observación runtime de style attributes.');
need(runtime.includes("attributeFilter:['style']"),'MutationObserver no está acotado al atributo style.');
need(runtime.includes('blockingEnabled:false'),'V31.21 debe ser observacional, no bloquear estilos.');
need(runtime.includes('trStyleSourceBaseline'),'Falta baseline estática del build.');
need(inlineAttributes>0,'La prueba esperaba deuda inline existente para inventariar.');
need(cssomWrites>0,'La prueba esperaba escrituras CSSOM existentes para inventariar.');
if(fail.length){console.error('Style boundary verification FAILED');for(const f of fail)console.error(' - '+f);process.exit(1);}
console.log('Style boundary verification OK');
console.log(` - Source style attributes: ${inlineAttributes}`);
console.log(` - Source CSSOM writes: ${cssomWrites}`);
console.log(' - Runtime observer: enabled');
console.log(' - CSP blocking: intentionally deferred');
