import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {globalSurfaceInventory} from './global-surface-inventory.mjs';
import {TR_APP_GLOBAL_PRUNE_NAMES} from './app-global-prune-transform.mjs';
import {TR_STATE_REGISTRY_MIGRATION_NAMES} from './state-registry-migration-transform.mjs';
import {TR_UI_REGISTRY_MIGRATION_NAMES} from './ui-registry-migration-transform.mjs';
import {TR_RESIDUAL_MIRROR_CLOSURE_NAMES,TR_DASHBOARD_UNIT_CONTRACT_NAME,TR_DYNAMIC_ACTION_CONTRACT_NAMES} from './residual-mirror-closure-transform.mjs';
const pkg=JSON.parse(fs.readFileSync('package.json','utf8')),v=pkg.version,file='dist/index.html',fail=[];
const need=(c,m)=>{if(!c)fail.push(m);},readJson=n=>fs.existsSync(n)?JSON.parse(fs.readFileSync(n,'utf8')):null;
if(!fs.existsSync(file)){console.error('Build verification FAILED: dist/index.html missing');process.exit(1);}
const h=fs.readFileSync(file,'utf8'),count=s=>h.split(s).length-1,size=Buffer.byteLength(h);
for(const [m,n] of [['data-tr-build',2],['data-tr-style-attr-runtime',1],['data-tr-reports-purity-runtime',1],['data-tr-structural-runtime',1],['data-tr-state-runtime',1],['data-tr-security-runtime',1],['data-tr-event-runtime',1],['data-tr-csp-runtime',1],['data-tr-style-runtime',1],['data-tr-operation-cleanup-runtime',1],['data-tr-render-closure-runtime',1]])need(count(`${m}="${v}"`)===n,`${m}: expected ${n}`);
need(count('<!doctype html>')===1,'doctype duplicated');need(count('function modalShell(title,body,footer)')===1,'app.js duplicated/corrupted');need(size<=3_000_000,`bundle unexpectedly large: ${size}`);
need(!/<script\s+src=["'](?:app|style-attr-runtime|reports-purity-runtime|structural-runtime|state-runtime|security-runtime|event-runtime|csp-runtime|style-runtime|operation-cleanup-runtime|render-closure-runtime)\.js["']/i.test(h),'local runtime script src remains');need(!/<link\s+rel=["']stylesheet["']\s+href=["']styles\.css["']/i.test(h),'styles.css link remains');
const scripts=[...h.matchAll(/<script\s+([^>]*)>([\s\S]*?)<\/script>/gi)].filter(m=>/data-tr-(?:build|style-attr-runtime|reports-purity-runtime|structural-runtime|state-runtime|security-runtime|event-runtime|csp-runtime|style-runtime|operation-cleanup-runtime|render-closure-runtime)=/.test(m[1]));need(scripts.length===11,`expected 11 bundled JS blocks, got ${scripts.length}`);
const r=readJson('dist/render-inventory.json');need(!!r,'render inventory missing');if(r){need(r.source?.assignments===12&&r.source?.declarations===1&&r.source?.baseAliases===5,'source render inventory changed');need(r.bundled?.assignments===0&&r.bundled?.declarations===1&&r.bundled?.baseAliases===0&&r.bundled?.destructiveRootWrites===1,'bundled render inventory changed');need(r.removedAssignments===12,'render removal count changed');}
const s=readJson('dist/state-action-inventory.json');need(!!s,'state action inventory missing');if(s){need(s.bridge===true,'State Action Bridge marker missing');need(Number(s.resolveCalls)>=14&&Number(s.publishCalls)>=19,'State Action Bridge counts low');need(Number(s.crossRuntimeWindowReads)===0,'State Action Bridge reopened direct cross-runtime reads');need(Number(s.targetActions)===61,'State Action targets changed');}
const p=readJson('dist/app-global-prune-inventory.json');need(!!p,'app global prune inventory missing');if(p){need(String(p.version)==='31.23.10','App global prune version changed');need(Number(p.before?.objectAssignBlocks)===51&&Number(p.after?.objectAssignBlocks)===44,'App prune blocks changed');need(Number(p.before?.objectAssignEntries)===375&&Number(p.after?.objectAssignEntries)===325,'App prune entries changed');need(Number(p.before?.objectAssignUnique)===332&&Number(p.after?.objectAssignUnique)===286,'App prune unique changed');need(Number(p.dynamicActionGuard?.dynamicHandlerSlots)===4&&Number(p.dynamicActionGuard?.protectedDynamicGlobals)===3,'Dynamic source guard changed');}
const sm=readJson('dist/state-registry-migration-inventory.json');need(!!sm,'State migration inventory missing');if(sm){need(String(sm.version)==='31.23.18','State migration version changed');need(String(sm.finalBindingVersion)==='31.23.41'&&Number(sm.finalBindingRefreshEntries)===56,'State final binding closure inventory changed');need((sm.names||[]).length===56,'State migrated names changed');need(Object.values(sm.batches||{}).length===7&&Object.values(sm.batches||{}).every(x=>x.length===8),'State batches changed');need(Number(sm.registryEntries)===63,'State registry publications changed');need(Number(sm.before?.blocks)===44&&Number(sm.after?.blocks)===42&&Number(sm.before?.entries)===325&&Number(sm.after?.entries)===262&&Number(sm.before?.unique)===286&&Number(sm.after?.unique)===230,'State migration inventory changed');}
const ui=readJson('dist/ui-registry-migration-inventory.json');need(!!ui,'UI migration inventory missing');if(ui){need(String(ui.version)==='31.23.47',`UI migration version ${ui.version}`);need(String(ui.finalBindingVersion)==='31.23.41'&&Number(ui.finalBindingRefreshEntries)===221,'UI final binding closure inventory changed');need((ui.names||[]).length===221,'UI migrated names changed');const bs=Object.values(ui.batches||{});need(bs.length===28&&bs.slice(0,27).every(x=>x.length===8)&&bs[27]?.length===5,'UI batches changed');const expected=[8,8,11,9,8,8,9,8,9,8,8,8,10,8,9,9,8,8,8,10,10,10,9,8,12,8,9,9];need(Number(ui.registryEntries)===247&&expected.every((n,i)=>Number(ui[`batch${i+1}Entries`])===n),'UI registry publications changed');need(Number(ui.before?.blocks)===42&&Number(ui.after?.blocks)===10&&Number(ui.before?.entries)===262&&Number(ui.after?.entries)===15&&Number(ui.before?.unique)===230&&Number(ui.after?.unique)===9,'UI migration inventory changed');}
const rm=readJson('dist/residual-mirror-closure-inventory.json');need(!!rm,'Residual/Dynamic Contract Closure inventory missing');if(rm){need(String(rm.version)==='31.23.50',`Residual Contract Closure version ${rm.version}`);need((rm.names||[]).length===5&&rm.dashboardUnit==='setDashboardUnit'&&Number(rm.dashboardUnitClosed)===1,'Dashboard Unit Closure inventory changed');need((rm.dynamicActions||[]).length===3&&Number(rm.dynamicActionsClosed)===3&&TR_DYNAMIC_ACTION_CONTRACT_NAMES.every(n=>rm.dynamicActions.includes(n)),'Dynamic Action Closure inventory changed');need(Number(rm.before?.blocks)===10&&Number(rm.after?.blocks)===0&&Number(rm.before?.entries)===15&&Number(rm.after?.entries)===0&&Number(rm.before?.unique)===9&&Number(rm.after?.unique)===0,'Residual/Dynamic closure inventory changed');need(Number(rm.before?.directUnique)===9&&Number(rm.after?.directUnique)===4,'Residual direct assignment inventory changed');need(Number(rm.removedEntries)===15&&Number(rm.directMirrorsRemoved)===5&&Number(rm.occurrences?.setDashboardUnit)===2&&Number(rm.dashboardHandlerRefsRemoved)===5,'Residual/Dynamic closure removals changed');for(const n of TR_DYNAMIC_ACTION_CONTRACT_NAMES)need(Number(rm.occurrences?.[n])===1,`Dynamic publication count changed: ${n}`);need(Number(rm.legacyDragHandlersBefore)===4&&Number(rm.legacyDragHandlersAfter)===0&&Number(rm.dragDelegatedListeners)===4,'Dashboard drag delegation inventory changed');for(const t of ['dragstart','dragend','dragover','drop'])need(Number(rm.dragAttributeConversions?.[t])===1,`Drag attribute conversion changed: ${t}`);}
const d=readJson('dist/dynamic-action-inventory.json');need(!!d,'dynamic inventory missing');if(d){need(Number(d.dynamicHandlerSlots)===4&&Number(d.dynamicCandidateRoots)===8&&Number(d.protectedDynamicGlobals)===3,'dynamic source inventory changed');for(const n of TR_DYNAMIC_ACTION_CONTRACT_NAMES)need(d.names?.protectedDynamicGlobals?.includes(n),`dynamic source inventory missing ${n}`);}
const c=readJson('dist/prune-candidate-inventory.json');need(!!c,'prune candidate inventory missing');if(c)need(Number(c.safeCandidateCount)===0&&(c.safeCandidates||[]).length===0,'safe prune candidates remain');
const m=readJson('dist/remaining-global-contract-map.json');need(!!m,'contract map missing');if(m){need(String(m.version)==='31.23.11','contract map version changed');need(Number(m.remainingUnique)===0&&Number(m.classified)===0&&Number(m.unclassified)===0,'contract coverage changed');need(Number(m.multiContract)===0,'contract overlap changed');need(Number(m.byPrimary?.['state-action']||0)===0&&Number(m.byPrimary?.['ui-handler']||0)===0&&Number(m.byPrimary?.['dynamic-action']||0)===0,'primary contracts changed');need(Number(m.coverage?.directGlobalMirror)===0,'direct global mirrors remain');need(Number(m.coverage?.crossRuntimeRead)===0,'cross-runtime reads reopened');need(Number(m.names?.migrationFrontiers?.stateOnly?.length)===0&&Number(m.names?.migrationFrontiers?.handlerOnly?.length)===0,'migration frontiers changed');}
const app=scripts.find(x=>/data-tr-build=/.test(x[1]));if(app){need((app[2].match(/\brender\s*=\s*function\s*\(/g)||[]).length===0,'legacy render assignment remains');need((app[2].match(/^const renderV(?:21|30|312|313|314)Base=render;\s*$/gm)||[]).length===0,'dead render alias remains');const g=globalSurfaceInventory(app[2]);need(g.objectAssignBlocks===0&&g.objectAssignEntries===0&&g.objectAssignUnique===0,`bundled global inventory ${g.objectAssignBlocks}/${g.objectAssignEntries}/${g.objectAssignUnique}`);for(const n of TR_APP_GLOBAL_PRUNE_NAMES)need(!g.names.objectAssign.includes(n),`re-exported pruned ${n}`);for(const n of TR_STATE_REGISTRY_MIGRATION_NAMES)need(!g.names.objectAssign.includes(n),`re-exported State ${n}`);for(const n of TR_UI_REGISTRY_MIGRATION_NAMES){need(!g.names.objectAssign.includes(n),`re-exported UI ${n}`);need(app[2].includes(n),`lost lexical UI binding ${n}`);}for(const n of TR_RESIDUAL_MIRROR_CLOSURE_NAMES){need(!g.names.objectAssign.includes(n),`re-exported residual ${n}`);need(!g.names.direct.includes(n),`direct residual mirror remains ${n}`);need(app[2].includes(n),`lost lexical residual binding ${n}`);}need(!g.names.objectAssign.includes(TR_DASHBOARD_UNIT_CONTRACT_NAME),'setDashboardUnit re-exported to window');need(!/\bwindow\.setDashboardUnit\s*\(/.test(app[2]),'window.setDashboardUnit handler ref remains');need(app[2].includes('setDashboardUnit'),'lost lexical setDashboardUnit binding');for(const n of TR_DYNAMIC_ACTION_CONTRACT_NAMES){need(!g.names.objectAssign.includes(n),`dynamic action re-exported to window: ${n}`);need(app[2].includes(n),`lost dynamic lexical binding ${n}`);}need(!/(?:^|[\s<])(?:ondragstart|ondragend|ondragover|ondrop)\s*=/gm.test(app[2]),'legacy drag DOM0 attribute remains');for(const t of ['dragstart','dragend','dragover','drop'])need(app[2].includes(`data-tr-on${t}=`),`missing delegated drag data attribute ${t}`);need(app[2].includes('__trDynamicDragDiagnostics'),'missing dashboard drag diagnostics');const stateFinal=app[2].lastIndexOf('/* V31.23.41 State final binding closure */'),uiFinal=app[2].lastIndexOf('/* V31.23.41 UI final binding closure */'),dynamicFinal=app[2].lastIndexOf('/* V31.23.50 dynamic action contract closure */');need(stateFinal>=0&&uiFinal>stateFinal&&dynamicFinal>uiFinal,'final registry binding closure order changed');need(app[2].includes("__trStateFinalBindingClosure',{value:56")&&app[2].includes("__trUiFinalBindingClosure',{value:221")&&app[2].includes("__trResidualMirrorClosure',{value:5")&&app[2].includes("__trDashboardUnitContractClosure',{value:1")&&app[2].includes("__trDynamicActionContractClosure',{value:3"),'final registry binding runtime markers missing');}
const st=scripts.find(x=>/data-tr-state-runtime=/.test(x[1]));if(st){need(st[2].includes('V31.23.6 STATE ACTION BRIDGE'),'State bridge missing');for(const n of ['confirmImportPreview','deleteImportBatch','editOperation','openOperationModal','saveInstrument','saveOperationFromForm','v314ImportExecFile','v314ImportMarketFile','v319SyncExecutionSetsToOperations'])need(!new RegExp(`\\bwindow\\.${n}\\b`).test(st[2]),`State Runtime reads window.${n}`);}
const oc=scripts.find(x=>/data-tr-operation-cleanup-runtime=/.test(x[1]));if(oc){need(oc[2].includes('V31.23.52 RUNTIME · Operation Cleanup Controls'),'Operation Cleanup runtime marker missing');need(oc[2].includes("Object.assign(registry,{openOperationModal,deleteOperation,deleteOperationImage})"),'Operation Cleanup registry publication missing');need(oc[2].includes("__trOperationCleanupDiagnostics"),'Operation Cleanup diagnostics missing');need(oc[2].includes("await deleteImageBlob(im.id)")&&oc[2].includes("state.operations=state.operations.filter(x=>x.id!==id)"),'Operation deletion cleanup contract missing');need(oc[2].includes("await deleteImageBlob(imageId)")&&oc[2].includes("o.images=(o.images||[]).filter(x=>x.id!==imageId)"),'Operation image deletion contract missing');}else need(false,'Operation Cleanup runtime missing from bundle');
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'tr-build-check-'));try{scripts.forEach((x,i)=>{const q=path.join(tmp,`block-${i}.js`);fs.writeFileSync(q,x[2].replace(/<\\\/script/gi,'</script'));const z=spawnSync(process.execPath,['--check',q],{encoding:'utf8'});need(z.status===0,`inline JS block ${i} syntax error`);});}finally{fs.rmSync(tmp,{recursive:true,force:true});}
if(fail.length){console.error('Build verification FAILED');for(const x of fail)console.error(' - '+x);process.exit(1);}
console.log('Build verification OK');console.log(' - Single HTML document: yes');console.log(' - Bundled JS blocks: 11/11, syntax OK');console.log(' - Canonical render closure: bundled + inventoried');console.log(' - State Action Bridge: bundled + inventoried, 0 direct cross-runtime window reads');console.log(' - App explicit window export pruning: 51 -> 44 blocks; 375 -> 325 entries; 332 -> 286 unique exports');console.log(' - State Registry Migration VII cumulative: 56 names; explicit window blocks 44 -> 42; entries 325 -> 262; unique 286 -> 230');console.log(' - UI Registry Migration XXVIII FINAL: 221 names; explicit window blocks 42 -> 10; entries 262 -> 15; unique 230 -> 9');console.log(' - Residual Mirror Closure V31.23.48: 5 mirrors remain closed');console.log(' - Dashboard Unit Contract Closure V31.23.49: setDashboardUnit remains registry-only');console.log(' - Dynamic Action Contract Closure V31.23.50: 3 Dashboard drag actions moved registry-only; drag DOM0 4 -> 0; explicit window blocks/entries/unique 10/15/9 -> 0/0/0');console.log(' - Operation Cleanup Controls V31.23.52: deleteOperation + deleteOperationImage registry-only, image blobs cleaned');console.log(' - Registry Final Binding Closure: State 56 + UI 221 + residual 5 + dashboard unit 1 + dynamic 3 bindings refreshed');console.log(' - Remaining Global Contract Map: 0 explicit contracts; State/UI frontiers 0/0; cross-runtime 0; direct mirrors 0');console.log(' - Dynamic Action Guard: source still identifies 4 dynamic slots / 8 roots / 3 historically protected actions; bundle closure is registry-only');console.log(` - Output size: ${size} bytes`);
