import fs from 'node:fs';
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
const index=fs.readFileSync('index.html','utf8');
const build=fs.readFileSync('build.mjs','utf8');
const runtime=fs.readFileSync('csp-runtime.js','utf8');
const fail=[];const need=(c,m)=>{if(!c)fail.push(m);};
need(pkg.version==='31.21.1',`Versión inesperada ${pkg.version}`);
need(index.includes('trading-research-source-version" content="31.21.1"'),'source-version no es 31.21.1.');
need(index.includes('<script src="csp-runtime.js"></script>'),'index.html no carga csp-runtime.js.');
need(index.indexOf('csp-runtime.js')>index.indexOf('event-runtime.js'),'csp-runtime.js debe cargar después de event-runtime.js.');
need(index.includes('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.112.3/dist/umd/supabase.js'),'Supabase SDK no está fijado a 2.112.3 UMD.');
need(!index.includes('@supabase/supabase-js@2"></script>'),'Supabase conserva la versión flotante @2.');
need(runtime.includes("const TR_CSP_RUNTIME_VERSION='31.20.0'"),'Runtime CSP con versión incorrecta.');
need(runtime.includes("styleAttrCompatibility:true"),'La deuda de style-src-attr debe quedar explícita.');
need(runtime.includes("fetch(location.href,{method:'HEAD'"),'Falta sonda runtime de cabecera CSP.');
need(build.includes("fs.writeFileSync('dist/_headers'"),'Build no genera _headers.');
need(build.includes("script-src-attr 'none'"),'Build no bloquea script-src-attr.');
need(build.includes("style-src-attr 'unsafe-inline'"),'Build no declara compatibilidad temporal de estilos inline.');
need(!/unsafe-eval/.test(build),'Build contiene unsafe-eval.');
need(!/unsafe-inline[^'\"]*['\"]?[^\n]*script-src/.test(build),'Build parece permitir unsafe-inline para scripts.');
if(fail.length){console.error('CSP source verification FAILED');for(const f of fail)console.error(' - '+f);process.exit(1);}
console.log('CSP source verification OK');
console.log(' - Supabase SDK: pinned 2.112.3 UMD');
console.log(' - script-src-attr: none');
console.log(' - unsafe-eval: absent');
console.log(' - style-src-attr: explicit compatibility debt');
