import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {globalSurfaceInventory} from './global-surface-inventory.mjs';
import {TR_APP_GLOBAL_PRUNE_NAMES} from './app-global-prune-transform.mjs';
import {TR_STATE_REGISTRY_MIGRATION_NAMES} from './state-registry-migration-transform.mjs';
import {TR_UI_REGISTRY_MIGRATION_NAMES} from './ui-registry-migration-transform.mjs';
const pkg=JSON.parse(fs.readFileSync('package.json','utf8')),v=pkg.version,file='dist/index.html',fail=[];
const need=(c,m)=>{if(!c)fail.push(m);},readJson=n=>fs.existsSync(n)?JSON.parse(fs.readFileSync(n,'utf8')):null;
if(!fs.existsSync(file)){console.error('Build verification FAILED: dist/index.html missing');process.exit(1);}
const h=fs.readFileSync(file,'utf8'),count=s=>h.split(s).length-1,size=Buffer.byteLength(h);
for(const [m,n] of [['data-tr-build',2],['data-tr-style-attr-runtime',1],['data-tr-reports-purity-runtime',1],['data-tr-structural-runtime',1],['data-tr-state-runtime',1],['data-tr-security-runtime',1],['data-tr-event-runtime',1],['data-tr-csp-runtime',1],['data-tr-style-runtime',1],['data-tr-render-closure-runtime',1]])need(count(`${m}="${v}"`)===n,`${m}: expected ${n}`);
need(count('<!doctype html>')===1,'doctype duplicated');need(count('function modalShell(title,body,footer)')===1,'app.js duplicated/corrupted');need(size<=3_000_000,`bundle unexpectedly large: ${size}`);
need(!/<script\s+src=["'](?:app|style-attr-runtime|reports-purity-runtime|structural-runtime|state-runtime|security-runtime|event-runtime|csp-runtime|style-runtime|render-closure-runtime)\.js["']/i.test(h),'local runtime script src remains');need(!/<link\s+rel=["']stylesheet["']\s+href=["']styles\.css["']/i.test(h),'styles.css link remains');
const scripts=[...h.matchAll(/<script\s+([^>]*)>([\s\S]*?)<\/script>/gi)].filter(m=>/data-tr-(?:build|style-attr-runtime|reports-purity-runtime|structural-runtime|state-runtime|security-runtime|event-runtime|csp-runtime|style-runtime|render-closure-runtime)=/.test(m[1]));need(scripts.length===10,`expected 10 bundled JS blocks, got ${scripts.length}`);
const r=readJson('dist/render-inventory.json');need(!!r,'render inventory missing');if(r){need(r.source?.assignments===12&&r.source?.declarations===1&&r.source?.baseAliases===5,'source render inventory changed');need(r.bundled?.assignments===0&&r.bundled?.declarations===1&&r.bundled?.baseAliases===0&&r.bundled?.destructiveRootWrites===1,'bundled render inventory changed');need(r.removedAssignments===12,'render removal count changed');}
const s=readJson('dist/state-action-inventory.json');need(!!s,'state action inventory missing');if(s){need(s.bridge===true,'State Action Bridge marker missing');need(Number(s.resolveCalls)>=14&&Number(s.publishCalls)>=19,'State Action Bridge counts low');need(Number(s.crossRuntimeWindowReads)===0,'State Action Bridge reopened direct cross-runtime reads');need(Number(s.targetActions)===61,'State Action targets changed');}
const p=readJson('dist/app-global-prune-inventory.json');need(!!p,'app global prune inventory missing');if(p){need(String(p.version)==='31.23.10','App global prune version changed');need(Number(p.before?.objectAssignBlocks)===51&&Number(p.after?.objectAssignBlocks)===44,'App prune blocks changed');need(Number(p.before?.objectAssignEntries)===375&&Number(p.after?.objectAssignEntries)===325,'App prune entries changed');need(Number(p.before?.objectAssignUnique)===332&&Number(p.after?.objectAssignUnique)===286,'App prune unique changed');need(Number(p.dynamicActionGuard?.dynamicHandlerSlots)===4&&Number(p.dynamicActionGuard?.protectedDynamicGlobals)===3,'Dynamic guard changed');}
const sm=readJson('dist/state-registry-migration-inventory.json');need(!!sm,'State migration inventory missing');if(sm){need(String(sm.version)==='31.23.18','State migration version changed');need(String(sm.finalBindingVersion)==='31.23.41'&&Number(sm.finalBindingRefreshEntries)===56,'State final binding closure inventory changed');need((sm.names||[]).length===56,'State migrated names changed');need(Object.values(sm.batches||{}).length===7&&Object.values(sm.batches||{}).every(x=>x.length===8),'State batches changed');need(Number(sm.registryEntries)===63,'State registry publications changed');need(Number(sm.before?.blocks)===44&&Number(sm.after?.blocks)===42&&Number(sm.before?.entries)===325&&Number(sm.after?.entries)===262&&Number(sm.before?.unique)===286&&Number(sm.after?.unique)===230,'State migration inventory changed');}
const ui=readJson('dist/ui-registry-migration-inventory.json');need(!!ui,'UI migration inventory missing');if(ui){need(String(ui.version)==='31.23.46',`UI migration version ${ui.version}`);need(String(ui.finalBindingVersion)==='31.23.41'&&Number(ui.finalBindingRefreshEntries)===216,'UI final binding closure inventory changed');need((ui.names||[]).length===216,'UI migrated names changed');need(Object.values(ui.batches||{}).length===27&&Object.values(ui.batches||{}).every(x=>x.length===8),'UI batches changed');const expected=[8,8,11,9,8,8,9,8,9,8,8,8,10,8,9,9,8,8,8,10,10,10,9,8,12,8,9];need(Number(ui.registryEntries)===238&&expected.every((n,i)=>Number(ui[`batch${i+1}Entries`])===n),'UI registry publications changed');need(Number(ui.before?.blocks)===42&&Number(ui.after?.blocks)===11&&Number(ui.before?.entries)===262&&Number(ui.after?.entries)===24&&Number(ui.before?.unique)===230&&Number(ui.after?.unique)===14,'UI migration inventory changed');}
const d=readJson('dist/dynamic-action-inventory.json');need(!!d,'dynamic inventory missing');if(d){need(Number(d.dynamicHandlerSlots)===4&&Number(d.dynamicCandidateRoots)===8&&Number(d.protectedDynamicGlobals)===3,'dynamic inventory changed');for(const n of ['v311DashboardDragEnd','v311DashboardDragStart','v311DashboardDrop'])need(d.names?.protectedDynamicGlobals?.includes(n),`dynamic inventory missing ${n}`);}
const c=readJson('dist/prune-candidate-inventory.json');need(!!c,'prune candidate inventory missing');if(c)need(Number(c.safeCandidateCount)===0&&(c.safeCandidates||[]).length===0,'safe prune candidates remain');
const m=readJson('dist/remaining-global-contract-map.json');need(!!m,'contract map missing');if(m){need(String(m.version)==='31.23.11','contract map version changed');need(Number(m.remainingUnique)===14&&Number(m.classified)===14&&Number(m.unclassified)===0,'contract coverage changed');need(Number(m.multiContract)===6,'contract overlap changed');need(Number(m.byPrimary?.['state-action'])===4&&Number(m.byPrimary?.['ui-handler'])===7&&Number(m.byPrimary?.['dynamic-action'])===3,'primary contracts changed');need(Number(m.coverage?.crossRuntimeRead)===0,'cross-runtime reads reopened');need(Number(m.names?.migrationFrontiers?.stateOnly?.length)===0&&Number(m.names?.migrationFrontiers?.handlerOnly?.length)===5,'migration frontiers changed');}
const app=scripts.find(x=>/data-tr-build=/.test(x[1]));if(app){need((app[2].match(/\brender\s*=\s*function\s*\(/g)||[]).length===0,'legacy render assignment remains');need((app[2].match(/^const renderV(?:21|30|312|313|314)Base=render;\s*$/gm)||[]).length===0,'dead render alias remains');const g=globalSurfaceInventory(app[2]);need(g.objectAssignBlocks===11&&g.objectAssignEntries===24&&g.objectAssignUnique===14,`bundled global inventory ${g.objectAssignBlocks}/${g.objectAssignEntries}/${g.objectAssignUnique}`);for(const n of TR_APP_GLOBAL_PRUNE_NAMES)need(!g.names.objectAssign.includes(n),`re-exported pruned ${n}`);for(const n of TR_STATE_REGISTRY_MIGRATION_NAMES)need(!g.names.objectAssign.includes(n),`re-exported State ${n}`);for(const n of TR_UI_REGISTRY_MIGRATION_NAMES){need(!g.names.objectAssign.includes(n),`re-exported UI ${n}`);need(app[2].includes(n),`lost lexical UI binding ${n}`);}const stateFinal=app[2].lastIndexOf('/* V31.23.41 State final binding closure */'),uiFinal=app[2].lastIndexOf('/* V31.23.41 UI final binding closure */');need(stateFinal>=0&&uiFinal>stateFinal,'final registry binding closure order changed');need(app[2].includes("__trStateFinalBindingClosure',{value:56")&&app[2].includes("__trUiFinalBindingClosure',{value:216"),'final registry binding runtime markers missing');}
const st=scripts.find(x=>/data-tr-state-runtime=/.test(x[1]));if(st){need(st[2].includes('V31.23.6 STATE ACTION BRIDGE'),'State bridge missing');for(const n of ['confirmImportPreview','deleteImportBatch','editOperation','openOperationModal','saveInstrument','saveOperationFromForm','v314ImportExecFile','v314ImportMarketFile','v319SyncExecutionSetsToOperations'])need(!new RegExp(`\\bwindow\\.${n}\\b`).test(st[2]),`State Runtime reads window.${n}`);}
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'tr-build-check-'));try{scripts.forEach((x,i)=>{const q=path.join(tmp,`block-${i}.js`);fs.writeFileSync(q,x[2].replace(/<\\\/script/gi,'</script'));const z=spawnSync(process.execPath,['--check',q],{encoding:'utf8'});need(z.status===0,`inline JS block ${i} syntax error`);});}finally{fs.rmSync(tmp,{recursive:true,force:true});}
if(fail.length){console.error('Build verification FAILED');for(const x of fail)console.error(' - '+x);process.exit(1);}
console.log('Build verification OK');console.log(' - Single HTML document: yes');console.log(' - Bundled JS blocks: 10/10, syntax OK');console.log(' - Canonical render closure: bundled + inventoried');console.log(' - State Action Bridge: bundled + inventoried, 0 direct cross-runtime window reads');console.log(' - App explicit window export pruning: 51 -> 44 blocks; 375 -> 325 entries; 332 -> 286 unique exports');console.log(' - State Registry Migration VII cumulative: 56 names; explicit window blocks 44 -> 42; entries 325 -> 262; unique 286 -> 230');console.log(' - UI Registry Migration XXVII cumulative: 216 names; explicit window blocks 42 -> 11; entries 262 -> 24; unique 230 -> 14');console.log(' - Registry Final Binding Closure: State 56 + UI 216 final bindings refreshed');console.log(' - Remaining Global Contract Map: 14/14 classified; primary State 4 / handler 7 / dynamic 3; State frontier 0; handler frontier 5; cross-runtime 0');console.log(' - Dynamic Action Guard: 4 dynamic slots; 8 candidate roots; 3 protected exported globals');console.log(` - Output size: ${size} bytes`);
